#!/bin/bash
VERSION=`git rev-list --all | wc -l`-`git rev-parse --short HEAD`-`date +%s`
echo $VERSION
echo $VERSION > VERSION
./bin/buildout
rm -rf /tmp/checkout
git clone . /tmp/checkout/
cd /tmp/checkout
git reset --hard origin/master
cd -
./bin/buildout-source-release file:///tmp/checkout buildout.cfg -n tasksitter-$VERSION
mv tasksitter-$VERSION.tgz releases/
echo "Release created, file: tasksitter-$VERSION.tgz"
